### ISSUE TITLE
[Bug]:New Update (isn't) removed icon?

### ISSUE THREAD

**Issue by richard-d-vindico** [RedisInsight/RedisInsight#1554] opened 2023-01-03 11:41 UTC
I've opened RedisInsight today and was informed update v2.16 was available, but when I closed Insight to update it, it removed the program icon and now tells me update v2.16 is pending even though Insight says I'm v2.2, but now the only way to find or open it is to run the installer?

Windows 11 Home (22H2)

**Comment by ViktarStarastsenka** [comment] 2023-01-03 17:34
hi @richard-d-vindico , if your previous RedisInsight version was 2.2, you may find some difficulties with automatic updates (due to some changes made later), please run the installer, and all the subsequent updates will be installed automatically.

**Comment by richard-d-vindico** [comment] 2023-01-03 17:49
Hi, My current version is 2.2.0, but I get the 2.16.0 update message every time I open RedisInsight, and I have to run the installer every time I want to open Insight as the program has ‘disappeared’?   Richard DentonSenior Developer01554 858 108 | www.vindico.net |Parc y Scarlets | Llanelli | SA14 9UZ Latest news: We have released our sign in/out and track & Trace app SWAPP - Read more here  From: ViktarStarastsenkaSent: 03 January 2023 17:35To: RedisInsight/RedisInsightCc: Richard; MentionSubject: Re: [RedisInsight/RedisInsight] [Bug]:New Update (isn't) removed icon? (Issue #1554) hi @richard-d-vindico , if your previous RedisInsight version was 2.2, you may find some difficulties with automatic updates (due to some changes made later), please run the installer, and all the subsequent updates will be installed automatically.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ViktarStarastsenka** [comment] 2023-01-03 17:58
@richard-d-vindico , can you just delete RedisInsight and then run the installer?
please let me know if this issue will still be reproducible.

**Closed** 2023-02-06 13:07 UTC
Labels: bug
