### ISSUE TITLE
Overview of all databases

### ISSUE THREAD

**Issue by kim-vetisearch** [RedisInsight/RedisInsight#2499] opened 2023-08-21 09:44 UTC
**Problem description** 
I have to select database one at a time, to see the available keys.

**How often do you encounter this problem** 
Every time I use RedisInsight

**Alternatives considered** It would be delightful to have a database overview as in the old APP (RESP.app) where all databases is shown with a count of keys e.g. "db0 (12)"

**Comment by ViktarStarastsenka** [comment] 2024-03-28 18:23
closing this ticket as this is a duplicate of https://github.com/RedisInsight/RedisInsight/issues/1857.

**Closed** 2024-03-28 18:23 UTC
Labels: feature
