### ISSUE TITLE
[Feature Request]:The version adds international processing and supports the use experience of mainstream language groups

### ISSUE THREAD

**Issue by haha34** [RedisInsight/RedisInsight#3812] opened 2024-09-11 06:16 UTC
Please add Chinese language support！

**Comment by ViktarStarastsenka** [comment] 2024-09-11 06:19
hi, this is a duplicate of https://github.com/RedisInsight/RedisInsight/issues/1317

**Closed by ViktarStarastsenka** 2024-09-11 06:19 UTC
Labels: feature
