### ISSUE TITLE
[Bug]:Request Timeout autodiscover Database

### ISSUE THREAD

**Issue by joeleclems** [RedisInsight/RedisInsight#525] opened 2022-04-13 09:29 UTC
**Steps to reproduce** (How to reproduce what you found step by step)
Add redis database (Autodiscover Databases)
Connect to Redis Enterprise Cluster with a cluster containing a lot of databases (we have 1260 databases in our cluster)

**Actual behavior** (A short description of what you found)
Request Timeout Error

**Expected behavior** (A short description of what you expected to find)
No timeout, just waiting for result. Perhaps add the possibility to set this timeout?

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://user-images.githubusercontent.com/11462557/163144649-467cc452-a639-4a00-9783-9194c1d4d3d4.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Redis insight v2.0.5

**Comment by ViktarStarastsenka** [comment] 2022-05-27 13:28
Hi @joeleclems , you can change a value of the timeout variable. Example for Linux to set the timeout to 100 seconds (100000 ms).
REQUEST_TIMEOUT=100000 ./RedisInsight-v2-linux-x86_64.AppImage

**Comment by ViktarStarastsenka** [comment] 2022-06-09 15:36
Hello @joeleclems, did you happen to try the workaround described above?

**Comment by ViktarStarastsenka** [comment] 2022-06-27 15:30
Hi @joeleclems , this issue should be fixed with 2.4.0 (released today). Could you please try it and let me know?

**Comment by ViktarStarastsenka** [comment] 2022-06-30 07:59
@joeleclems , did you have a chance to try the fix?

**Comment by ViktarStarastsenka** [comment] 2022-07-08 07:58
@joeleclems , please re-open the ticket if the issue is still relevant

**Comment by joeleclems** [comment] 2022-07-20 09:42
Hi @ViktarStarastsenka 

I try with version 2.4.0 : it's better, but not working completely.
Now i can select the databases, no more timeout problem.
When i try to add all databases, i have this message : 
![image](https://user-images.githubusercontent.com/11462557/179951258-3373f4fb-a6b8-46d1-a2cb-3e2add25675e.png)

**Comment by joeleclems** [comment] 2022-07-20 16:03
@ViktarStarastsenka 
There is no tooltip in user interface, this is the logs : 
[redisinsight-2022-07-20.log](https://github.com/RedisInsight/RedisInsight/files/9151764/redisinsight-2022-07-20.log)
[redisinsight-errors-2022-07-20.log](https://github.com/RedisInsight/RedisInsight/files/9151766/redisinsight-errors-2022-07-20.log)
The "new ui" with new test : 
![image](https://user-images.githubusercontent.com/11462557/180029545-e1561ddc-f0ee-49c4-8440-7228a015e201.png)

**Comment by ViktarStarastsenka** [comment] 2022-07-22 07:22
@joeleclems , are you able to add one (just one) database from this list?
to double check that there is no connection issues.

**Comment by ViktarStarastsenka** [comment] 2023-02-06 14:43
hi @joeleclems , please try to use no more than ~400 databases per cluster (ideally even less), and add them in batches - in this case, RedisInsight should be able to process them.
please re-open the ticket if the issue will still be relevant.

**Closed by ViktarStarastsenka** 2023-02-06 14:43 UTC
Labels: bug
