### ISSUE TITLE
[Bug]:The lowercase hgetall cannot retrieve hash data

### ISSUE THREAD

**Issue by xiaohuo1229** [RedisInsight/RedisInsight#3586] opened 2024-07-02 11:15 UTC
When I tried to practice storing hash data through commands, I successfully stored a set of data using "hset demo a 1 b 2 c 3 d 4". However, when I used "hgetall demo" to retrieve the data, it prompted "empty list or set". Then, I used "HGETALL demo" and successfully retrieved the data: 
"1) "a"
2) "1"
3) "b"
4) "2"
5) "c"
6) "3"
7) "d"
8) "4"
". After multiple tests, the lowercase "hgetall" cannot retrieve data.
![image](https://github.com/RedisInsight/RedisInsight/assets/45385414/8f771532-51a6-4112-8f5e-88f848f4929a)

Here is the result after restarting the computer: 
![image](https://github.com/RedisInsight/RedisInsight/assets/45385414/dce8d914-6897-4426-82f7-b8fe03ab32d3)

**Comment by ViktarStarastsenka** [comment] 2024-07-02 11:45
hi @xiaohuo1229 , this is a duplicate of https://github.com/RedisInsight/RedisInsight/issues/3465

**Closed by ViktarStarastsenka** 2024-07-02 11:45 UTC
