### ISSUE TITLE
[Feature Request]:Added Chinese page support

### ISSUE THREAD

**Issue by haha34** [RedisInsight/RedisInsight#3815] opened 2024-09-12 06:46 UTC
GUI page in English description, for developers used to Chinese, the experience is poor, hope the author in the next version to complete.

**Comment by ViktarStarastsenka** [comment] 2024-09-12 10:42
hi, this is a duplicate of https://github.com/RedisInsight/RedisInsight/issues/1317

**Closed by ViktarStarastsenka** 2024-09-12 10:42 UTC
Labels: feature
