### ISSUE TITLE
[Feature Request]:why not show database index list

### ISSUE THREAD

**Issue by kingdoing** [RedisInsight/RedisInsight#3585] opened 2024-07-02 10:23 UTC
it is not convenient to select dababase indexes and it is not known which database has data. It is good job, such as RDM.

**Comment by ViktarStarastsenka** [comment] 2024-07-02 10:26
this is a duplicate of https://github.com/RedisInsight/RedisInsight/issues/1857

**Closed by ViktarStarastsenka** 2024-07-02 10:26 UTC
Labels: feature
