### ISSUE TITLE
[Bug]: `Invalid regular expression` when running in Safari

### ISSUE THREAD

**Issue by marianhlavac** [RedisInsight/RedisInsight#1727] opened 2023-02-11 17:34 UTC
Opening RedisInsight in _Safari Version 16.2 (18614.3.7.1.5)_ results in blank page and following error message output in Javascript console, rendering it completely unusable:

```
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
	(anonymous function) (bundle.1a780e6b284ce7400617.min.js:2)
```

According to [this SO question](https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group) it might be relevant and caused by use of lookbehind in regexes, [which is not supported in Safari](https://caniuse.com/js-regexp-lookbehind).

**Steps to reproduce** 

- Run latest version of RedisInsight using `docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest`
- Navigate to localhost:8001 in Safari

**Additional context**

macOS 13.1  
Safari 16.2 
Redis 6.2.10 (using [this Docker image](https://hub.docker.com/layers/redis/redis-stack/latest/images/sha256-bcfdbac00398c5b8c92108a4588220d909b941c0ef2c0c73d120c9f4a17bc7a2?context=explore))

**Comment by ViktarStarastsenka** [comment] 2023-03-01 16:02
hi @marianhlavac , thank you for reporting this, will be fixed with 2.22 (late March).

**Comment by ViktarStarastsenka** [comment] 2023-03-30 15:43
@marianhlavac , please try it with 2.22 (released today).
re-open the ticket if the issue is still reproducible.

**Comment by ViktarStarastsenka** [comment] 2023-05-08 20:14
fixed with the latest version.
please re-open if the issue is still relevant.

**Closed by ViktarStarastsenka** 2023-05-08 20:14 UTC
Labels: bug
