### ISSUE TITLE
[Bug]: Again, Serialized Java Objects appear as scrambled text (Redis Insight v2.24)

### ISSUE THREAD

**Issue by Longwater1234** [RedisInsight/RedisInsight#2147] opened 2023-05-31 06:33 UTC
**Preconditions** (Any important steps we need to know)
This was patched in Redis Insight v2.10 issue #744 , but sadly it has returned again in v2.24 😑! By the way this issue is not present in latest v1 of Redis Insight (browser based). 

**Steps to reproduce** (How to reproduce what you found step by step)
Create a Java class, implement Serializable, and save it to Redis. Then view it in Redis Insight v2.24
 
**Actual behavior** (A short description of what you found)
The value appears as scrambled text. Unreadable. 

**Expected behavior** (A short description of what you expected to find)
Should appear as a JSON string as in RedisInsight v1, readable and clean, with "JAVA" label.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/RedisInsight/RedisInsight/assets/33986524/1fcc55ba-03ff-470b-a295-701f4a698b56)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Windows 10 Pro Version	22H2,  Redis  5.0.14.1, localhost connection

**Comment by ViktarStarastsenka** [comment] 2023-06-01 17:55
@Longwater1234, can you please check that the "JAVA" formatter is selected?

**Comment by Longwater1234** [comment] 2023-06-06 09:03
I don't fully understand what you mean.If you mean inside Redis Insight, It is not, it's shown as STRING.

**Comment by ViktarStarastsenka** [comment] 2023-06-06 09:14
@Longwater1234 , please try selecting a formatter
<img width="705" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/3f24ebf0-f6b2-4289-86ca-235121298e29">

**Comment by Longwater1234** [comment] 2023-06-07 04:23
Ok i did, and it worked for HASH but only 1 level deep. If more than 2 levels , still scrambled. Also SETS are still scrambled regardless. In v1 of RedisInsight, (for browser) works OK for all types.

**Comment by ViktarStarastsenka** [comment] 2023-06-07 08:21
@Longwater1234 , can you share an example of your data so I can look at it in more detail? but please sanitize it to remove any sensitive information

**Comment by Longwater1234** [comment] 2023-06-08 06:04
@ViktarStarastsenka  Ok , i made a small demo project here : https://github.com/Longwater1234/demo-redis

**Comment by Longwater1234** [comment] 2023-06-08 06:04
@ViktarStarastsenka  Ok , i made a small demo project here : https://github.com/Longwater1234/demo-redis

**Comment by ViktarStarastsenka** [comment] 2023-06-09 11:43
@Longwater1234 , thanks for the demo project
looks like the library we use to parse Serialized Java objects does not support this format.
Checked with previous RedisInsight 2.x versions - works the same, it was not supported before.
I'll look into what can be done here.

**Comment by AgentZh0u** [comment] 2023-07-13 01:46
I have encountered the same issue. Do we have an estimated timeline for the fix?

**Comment by ViktarStarastsenka** [comment] 2023-08-15 11:37
currently, there is no clear timeline, I'll post an update once it is known

**Comment by ViktarStarastsenka** [comment] 2023-08-31 14:29
@AgentZh0u , it should be fixed with 2.32 (released today).
please re-open the ticket if the issue still reproduces.

**Closed by ViktarStarastsenka** 2023-08-31 14:29 UTC
Labels: bug
