### ISSUE TITLE
[Feature Request]:please update 2.X docker image

### ISSUE THREAD

**Issue by zhuzhenkun** [RedisInsight/RedisInsight#519] opened 2022-04-10 11:05 UTC
please update 2.X docker image

**Comment by totoroliu0131** [comment] 2022-04-17 02:06
redisinsight 2.X looks good ! I also need 2.x docker image on docker hub plz

**Comment by mrmartan** [comment] 2022-07-22 12:28
Does anybody know why there is only the v1? Is there some docs about this? Are we supposed to build the v2 image ourselves?

**Comment by ViktarStarastsenka** [comment] 2022-07-22 12:35
@mrmartan , currently there is docker version of RedisInsight available for [Redis Stack ](https://redis.io/docs/stack/get-started/install/docker/)(but you cannot add any other databases).
Separate RedisInsight V2 docker image is planned to be released around September.

**Comment by mrmartan** [comment] 2022-07-22 12:47
We are an enterprise customer and want to deploy v2 on our kubernetes cluster.

**Comment by mrmartan** [comment] 2022-07-22 12:48
We also use CRDBs and I beleive redisinsight v1 does not support them.

**Comment by ViktarStarastsenka** [comment] 2022-07-22 16:28
@mrmartan , CRDB should work on any version/platform.

**Comment by ViktarStarastsenka** [comment] 2022-09-27 15:06
hi @linuxd3v, not in September. Currently, we work on the architecture to provide the best experience, I'll post the update with more accurate timelines when they are known.

**Comment by ToshY** [comment] 2022-10-03 21:46
As a friendly reminder: when adding the V2 image, please update the documentation on Dockerhub as well. It's currently completely empty, and with the wiki here seemingly outdated, it would be very much appreciated if up-to-date examples for docker & compose are added there.

**Comment by ChristofNasahl** [comment] 2022-11-10 08:18
Our team is also waiting for V2. Any ideas when it will be available?

**Comment by ViktarStarastsenka** [comment] 2022-11-10 09:11
hi @ChristofNasahl , it is planned to be delivered in H1 2023.

**Comment by linuxd3v** [comment] 2022-11-30 16:09
@ViktarStarastsenka we have several environments in aws: sandbox, dev, staging, prod and each of those environments could have: 20-30 self-hosted redis instances + read replicas.  
In addition to that  - devs cannot directly connect to these redis servers as they are not directly exposed to the internet and devs have to jump through bastion server.    
   
It would be a chore to ask every developer to configure all these connections (almost 200 connections) on their redis desktop GUI software manually and then keep up to date. So we just spun up RedisInsight instance in each environment so everyone can check the data in redis at any time, and then we can maintain connections in a centralized way.

**Comment by setchy** [comment] 2022-11-30 16:23
> @ViktarStarastsenka we have several environments in aws: sandbox, dev, staging, prod and each of those environments could have: 20-30 self-hosted redis instances + read replicas. In addition to that - devs cannot directly connect to these redis servers as they are not directly exposed to the internet and devs have to jump through bastion server.
> 
> It would be a chore to ask every developer to configure all these connections (almost 200 connections) on their redis desktop GUI software manually and then keep up to date. So we just spun up RedisInsight instance in each environment so everyone can check the data in redis at any time, and then we can maintain connections in a centralized way.

+1

**Comment by totoroliu0131** [comment] 2022-11-30 16:35
In our company, we use google cloud memory store redis to build our product, at the meanwhile we have multiple teams and each teams have its own redis instance. For now we run redisinsight 1.X on our GKE and only let dev team to use.

BTW a few month ago, I tried redis-stack on GKE and only use it's redisinsight, but when I connected to GCP redis and I got some connection error.

**Comment by ViktarStarastsenka** [comment] 2022-12-08 15:07
hi @totoroliu0131, thanks for sharing your use case. I believe the reason for this error is that RedisInsight on docker bundled with Redis Stack can work only with Redis Stack from this bundle.

**Comment by aru1001** [comment] 2022-12-16 20:29
eagerly waiting for this feature.. H1 2023 🤞

**Comment by m4n50n** [comment] 2023-01-20 13:23
Waiting for 2.x version in docker

**Comment by xinmans** [comment] 2023-01-25 14:27
i use 1.x  version in docker, very cool, so i need 2.x version in docker too.

**Comment by davama** [comment] 2023-03-01 22:53
Hello,

great app!!!

wondering what the ETA for v2.x docker image.

Thanks!

**Comment by Nipuns1999** [comment] 2023-03-30 06:42
are we able to set authentication? like multiple user sign-in's

**Comment by ViktarStarastsenka** [comment] 2023-03-30 08:18
@Nipuns1999 , if you use docker RedisInsight v1, you can set up a reverse proxy with LDAP integration. Instructions are here:
https://github.com/RedisInsight/RedisInsight-reverse-proxy
additionally, there is an option to authenticate users when they open a database (the list of databases will be visible to everyone who has access to RedisInsight, but you will need a database username and password to open it) - https://docs.redis.com/latest/ri/using-redisinsight/auth-database/

**Comment by adrianwebb** [comment] 2023-04-07 21:03
@ViktarStarastsenka I was wondering if you see any difficulties in cloning the repo and building the Docker image into an individual registry for the time being while you all are deciding the priority of this issue?  Also are there any good references to where I might find the environment variables if I built the image and deployed outside of an official capacity (even if it is which code files might point the way)?

In case you are wondering for prioritization, my use case is that we use RedisInsight as a way to bundle Redis observability and database management into our Kubernetes clusters across environments.  We have a generic chart where we deploy RedisInsight through ArgoCD, along with other database management utilities like Cloudbeaver (for relational database management) and in remote environments we put these tools behind an access controlled 2 factor SSO so that we can more easily debug if needed what is going on in production, qa, etc... environments with the same tools we use for development.  I also do not want to expose the managed Redis services outside the cluster nodes and manage IP connections from developers in IP whitelisting.  The only instances that have access to the managed Redis services are the Kubernetes nodes so it is necessary that RedisInsight live in an accessible environment.  In this scenario the desktop variant does not meet the needs, even though I have traditionally used RESP.app (which joined this project) on local Ubuntu for local container development.  

I am hoping some of the features for database key management (or that general UI) have made it into the 2.x versions because the key visibility / management functionality in my opinion is a major weakness of the RedisInsight v1 that has a container image available.  So bottom line is I want more of RESP.app feel in a remotely deployable form so it can work across environments.

I don't mean to sound ungrateful for the work that you are doing on this project (as I truly am) but until you have a containerized counterpart to your desktop variant this is really half a product and it seems given what you already have and the fact it gets built for RedisStack this would be super simple to implement and release (as a container image maintainer myself).  I really don't see why there is a huge delay here technically speaking.  Unless your marketing team is holding you back to collect emails, which would not be good for this project long term.

But to my original question, any gotchas or difficulties in building our own image and finding the requisite environment variables until you get the internal priorities straightened out?  Thanks!

**Comment by linuxd3v** [comment] 2023-05-08 15:12
There are couple images on dockerhub that package v2:   
https://hub.docker.com/r/muicoder/redisinsight

**Comment by xinmans** [comment] 2023-05-10 02:22
> There are couple images on dockerhub that package v2:   
> 
> https://hub.docker.com/r/muicoder/redisinsight 

Build docker by this image, but failure


Pls see below error
      
./docker-entry.sh: 19: ./docker-entry.sh: gnome-keyring-daemon: Operation not permitted
./docker-entry.sh: 21: ./docker-entry.sh: gnome-keyring-daemon: Operation not permitted

      
docker-compose.yml 
version: "3.8"
services:
  app:
    image: muicoder/redisinsight:2.24.0
    container_name: redisinsight_v2
    restart: unless-stopped
    ports:
      - 18001:8001
    volumes:
      - ./db:/db
    networks:
      - default

**Comment by davama** [comment] 2023-05-10 03:04
I also tried that image and got the same error…

dont think this issue is the proper place to troubleshoot 3rd party docker images.

avoid clutter for original issue at hand: v2.x on docker hub by redis folks

**Comment by krunal-jethva-tark** [comment] 2023-05-11 09:00
if you want redis_server and insight in one pack redis_stack is good option. It has insight 2.x
https://hub.docker.com/r/redis/redis-stack

**Comment by kiss-less** [comment] 2023-05-29 18:10
> I also tried that image and got the same error…
> 
> dont think this issue is the proper place to troubleshoot 3rd party docker images.
> 
> avoid clutter for original issue at hand: v2.x on docker hub by redis folks

Well, even if we build the image from the redis repo, using the Dockerfile from the main branch, the error is still there. Running the container with the full container capabilities (https://docs.docker.com/engine/reference/commandline/run/#privileged) seems to help with the error, however, the requests are not being properly processed. Probably, there are some issues either with the building process or with the configuration. I tried running it with NODE_DEBUG set to cluster,net,http,fs,tls,module,timers and here is what I got:


````
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
HTTP 1: AGENT socket.destroySoon()
NET 1: _final: not ended, call shutdown()
NET 1: _read
NET 1: afterShutdown destroyed=false ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: BufferList { head: null, tail: null, length: 0 },
  length: 0,
  pipes: [],
  flowing: true,
  ended: true,
  endEmitted: true,
  reading: false,
  constructed: true,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  resumeScheduled: false,
  errorEmitted: false,
  emitClose: false,
  autoDestroy: true,
  destroyed: false,
  errored: null,
  closed: false,
  closeEmitted: false,
  defaultEncoding: 'utf8',
  awaitDrainWriters: null,
  multiAwaitDrain: false,
  readingMore: false,
  dataEmitted: true,
  decoder: null,
  encoding: null,
  [Symbol(kPaused)]: false
}
NET 1: destroy
NET 1: close
NET 1: close handle
NET 1: emit close
HTTP 1: CLIENT socket onClose
HTTP 1: removeSocket raw.githubusercontent.com:443::::::::::::::::::::: writable: false
HTTP 1: HTTP socket close
NET 1: afterConnect
TLS 1: client _start handle? true connecting? false requestOCSP? false
NET 1: _read
NET 1: Socket._handle.readStart
NET 1: afterConnect
TLS 1: client _start handle? true connecting? false requestOCSP? false
NET 1: _read
NET 1: Socket._handle.readStart
TLS 1: client onhandshakedone
TLS 1: client _finishInit handle? true alpn false servername raw.githubusercontent.com
TLS 1: client emit secureConnect. authorized: true
TLS 1: client emit session
TLS 1: client onhandshakedone
TLS 1: client _finishInit handle? true alpn false servername raw.githubusercontent.com
TLS 1: client emit secureConnect. authorized: true
TLS 1: client emit session
HTTP 1: requestTimeout timer moved to req
HTTP 1: AGENT incoming response!
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
HTTP 1: AGENT socket.destroySoon()
NET 1: _final: not ended, call shutdown()
NET 1: _read
HTTP 1: requestTimeout timer moved to req
HTTP 1: AGENT incoming response!
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
HTTP 1: AGENT socket.destroySoon()
NET 1: _final: not ended, call shutdown()
NET 1: _read
NET 1: afterShutdown destroyed=false ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: BufferList { head: null, tail: null, length: 0 },
  length: 0,
  pipes: [],
  flowing: true,
  ended: true,
  endEmitted: true,
  reading: false,
  constructed: true,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  resumeScheduled: false,
  errorEmitted: false,
  emitClose: false,
  autoDestroy: true,
  destroyed: false,
  errored: null,
  closed: false,
  closeEmitted: false,
  defaultEncoding: 'utf8',
  awaitDrainWriters: null,
  multiAwaitDrain: false,
  readingMore: false,
  dataEmitted: true,
  decoder: null,
  encoding: null,
  [Symbol(kPaused)]: false
}
NET 1: destroy
NET 1: close
NET 1: close handle
NET 1: afterShutdown destroyed=false ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: BufferList { head: null, tail: null, length: 0 },
  length: 0,
  pipes: [],
  flowing: true,
  ended: true,
  endEmitted: true,
  reading: false,
  constructed: true,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  resumeScheduled: false,
  errorEmitted: false,
  emitClose: false,
  autoDestroy: true,
  destroyed: false,
  errored: null,
  closed: false,
  closeEmitted: false,
  defaultEncoding: 'utf8',
  awaitDrainWriters: null,
  multiAwaitDrain: false,
  readingMore: false,
  dataEmitted: true,
  decoder: null,
  encoding: null,
  [Symbol(kPaused)]: false
}
NET 1: destroy
NET 1: close
NET 1: close handle
NET 1: emit close
HTTP 1: CLIENT socket onClose
HTTP 1: removeSocket raw.githubusercontent.com:443::::::::::::::::::::: writable: false
HTTP 1: HTTP socket close
NET 1: emit close
HTTP 1: CLIENT socket onClose
HTTP 1: removeSocket raw.githubusercontent.com:443::::::::::::::::::::: writable: false
HTTP 1: HTTP socket close
NET 1: afterConnect
TLS 1: client _start handle? true connecting? false requestOCSP? false
NET 1: _read
NET 1: Socket._handle.readStart
NET 1: afterConnect
TLS 1: client _start handle? true connecting? false requestOCSP? false
NET 1: _read
NET 1: Socket._handle.readStart
TLS 1: client onhandshakedone
TLS 1: client _finishInit handle? true alpn false servername raw.githubusercontent.com
TLS 1: client emit secureConnect. authorized: true
TLS 1: client emit session
TLS 1: client onhandshakedone
TLS 1: client _finishInit handle? true alpn false servername raw.githubusercontent.com
TLS 1: client emit secureConnect. authorized: true
TLS 1: client emit session
HTTP 1: requestTimeout timer moved to req
HTTP 1: AGENT incoming response!
NET 1: _read
NET 1: _read
HTTP 1: AGENT socket.destroySoon()
NET 1: _final: not ended, call shutdown()
NET 1: _read
NET 1: afterShutdown destroyed=false ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: BufferList { head: null, tail: null, length: 0 },
  length: 0,
  pipes: [],
  flowing: true,
  ended: true,
  endEmitted: true,
  reading: false,
  constructed: true,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  resumeScheduled: false,
  errorEmitted: false,
  emitClose: false,
  autoDestroy: true,
  destroyed: false,
  errored: null,
  closed: false,
  closeEmitted: false,
  defaultEncoding: 'utf8',
  awaitDrainWriters: null,
  multiAwaitDrain: false,
  readingMore: false,
  dataEmitted: true,
  decoder: null,
  encoding: null,
  [Symbol(kPaused)]: false
}
NET 1: destroy
NET 1: close
NET 1: close handle
NET 1: emit close
HTTP 1: CLIENT socket onClose
HTTP 1: removeSocket raw.githubusercontent.com:443::::::::::::::::::::: writable: false
HTTP 1: HTTP socket close
HTTP 1: requestTimeout timer moved to req
HTTP 1: AGENT incoming response!
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
HTTP 1: AGENT socket.destroySoon()
NET 1: _final: not ended, call shutdown()
NET 1: _read
NET 1: afterShutdown destroyed=false ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: BufferList { head: null, tail: null, length: 0 },
  length: 0,
  pipes: [],
  flowing: true,
  ended: true,
  endEmitted: true,
  reading: false,
  constructed: true,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  resumeScheduled: false,
  errorEmitted: false,
  emitClose: false,
  autoDestroy: true,
  destroyed: false,
  errored: null,
  closed: false,
  closeEmitted: false,
  defaultEncoding: 'utf8',
  awaitDrainWriters: null,
  multiAwaitDrain: false,
  readingMore: false,
  dataEmitted: true,
  decoder: null,
  encoding: null,
  [Symbol(kPaused)]: false
}
NET 1: destroy
NET 1: close
NET 1: close handle
NET 1: emit close
HTTP 1: CLIENT socket onClose
HTTP 1: removeSocket raw.githubusercontent.com:443::::::::::::::::::::: writable: false
HTTP 1: HTTP socket close
NET 1: afterConnect
TLS 1: client _start handle? true connecting? false requestOCSP? false
NET 1: _read
NET 1: Socket._handle.readStart
NET 1: afterConnect
TLS 1: client _start handle? true connecting? false requestOCSP? false
NET 1: _read
NET 1: Socket._handle.readStart
TLS 1: client onhandshakedone
TLS 1: client _finishInit handle? true alpn false servername raw.githubusercontent.com
TLS 1: client emit secureConnect. authorized: true
TLS 1: client emit session
TLS 1: client onhandshakedone
TLS 1: client _finishInit handle? true alpn false servername raw.githubusercontent.com
TLS 1: client emit secureConnect. authorized: true
TLS 1: client emit session
HTTP 1: requestTimeout timer moved to req
HTTP 1: AGENT incoming response!
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
HTTP 1: AGENT socket.destroySoon()
NET 1: _final: not ended, call shutdown()
NET 1: _read
NET 1: afterShutdown destroyed=false ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: BufferList { head: null, tail: null, length: 0 },
  length: 0,
  pipes: [],
  flowing: true,
  ended: true,
  endEmitted: true,
  reading: false,
  constructed: true,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  resumeScheduled: false,
  errorEmitted: false,
  emitClose: false,
  autoDestroy: true,
  destroyed: false,
  errored: null,
  closed: false,
  closeEmitted: false,
  defaultEncoding: 'utf8',
  awaitDrainWriters: null,
  multiAwaitDrain: false,
  readingMore: false,
  dataEmitted: true,
  decoder: null,
  encoding: null,
  [Symbol(kPaused)]: false
}
NET 1: destroy
NET 1: close
NET 1: close handle
HTTP 1: requestTimeout timer moved to req
HTTP 1: AGENT incoming response!
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
NET 1: _read
HTTP 1: AGENT socket.destroySoon()
NET 1: _final: not ended, call shutdown()
NET 1: _read
NET 1: emit close
HTTP 1: CLIENT socket onClose
HTTP 1: removeSocket raw.githubusercontent.com:443::::::::::::::::::::: writable: false
HTTP 1: HTTP socket close
NET 1: afterShutdown destroyed=false ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: BufferList { head: null, tail: null, length: 0 },
  length: 0,
  pipes: [],
  flowing: true,
  ended: true,
  endEmitted: true,
  reading: false,
  constructed: true,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  resumeScheduled: false,
  errorEmitted: false,
  emitClose: false,
  autoDestroy: true,
  destroyed: false,
  errored: null,
  closed: false,
  closeEmitted: false,
  defaultEncoding: 'utf8',
  awaitDrainWriters: null,
  multiAwaitDrain: false,
  readingMore: false,
  dataEmitted: true,
  decoder: null,
  encoding: null,
  [Symbol(kPaused)]: false
}
NET 1: destroy
NET 1: close
NET 1: close handle
NET 1: emit close
HTTP 1: CLIENT socket onClose
HTTP 1: removeSocket raw.githubusercontent.com:443::::::::::::::::::::: writable: false
HTTP 1: HTTP socket close
````

Docker command to reproduce:

`docker run -it -v redisinsight:/db -e "NODE_DEBUG=cluster,net,http,fs,tls,module,timers" -p 8001:8001 --privileged <IMAGE_NAME:TAG>`

**Comment by hoangphuocbk** [comment] 2023-07-01 05:15
It works on my environment 👍🏼 
```
---
version: "3.8"
services:
  app:
    image: redisinsight:2.28.0
    container_name: redisinsight_v2
    restart: unless-stopped
    ports:
    - 5000:5000
    volumes:
    - ./db:/db
    cap_add:
    - IPC_LOCK
```

**Comment by linuxd3v** [comment] 2023-07-01 12:10
@hoangphuocbk how would it? I don't see it present in the dockerhub:     
https://hub.docker.com/r/redislabs/redisinsight/tags?page=1&name=2.28.0

**Comment by hoangphuocbk** [comment] 2023-07-01 12:57
> @hoangphuocbk how would it? I don't see it present in the dockerhub: https://hub.docker.com/r/redislabs/redisinsight/tags?page=1&name=2.28.0

You can pull image from muicoder/redisinsight:2.28.0

**Comment by ToshY** [comment] 2023-07-01 13:12
> > @hoangphuocbk how would it? I don't see it present in the dockerhub: https://hub.docker.com/r/redislabs/redisinsight/tags?page=1&name=2.28.0
> 
> You can pull image from muicoder/redisinsight:2.28.0

So that's just another unofficial image. Please don't clutter the thread with that, we're all just waiting for the official image to be released.

**Comment by hoangphuocbk** [comment] 2023-07-01 15:02
> > > @hoangphuocbk how would it? I don't see it present in the dockerhub: https://hub.docker.com/r/redislabs/redisinsight/tags?page=1&name=2.28.0
> > 
> > 
> > You can pull image from muicoder/redisinsight:2.28.0
> 
> So that's just another unofficial image. Please don't clutter the thread with that, we're all just waiting for the official image to be released.

Built image your self or use someone's image or waiting the offical image. It's **your choice**, you dont want to use other image but someone do.

It's **your choice**

**Comment by linuxd3v** [comment] 2023-07-05 10:48
> You can pull image from muicoder/redisinsight:2.28.0  
> So that's just another unofficial image.  
  
How awful. thank you for raising our awareness of this clearly working unofficial redisinsight image. Let this be a reminder for people not to use it (even though it works) - and  I'm for one ready to wait for the official image as many more years as it takes.

**Comment by adrianwebb** [comment] 2023-07-05 11:08
Maybe someone from the Redis Insight team can actually comment on this issue so that people will understand if this is even going to be a eventuality?  Look, people generally can't sit and wait for an issue like this that is clearly ignored by the Redis Insight team for eternity, so I personally have no problem with discussion of alternatives and if they work or not, because this helps resolve any technical challenges that the Redis Insight team need to resolve.  I actually don't think this is a technical decision as much as a marketing one, so I would not hold my breath on the Redis Insight team releasing one.  I never got an answer on my comment above from the Redis Insight team I posted months ago.  It doesn't take a lot of time to package a Docker file, and they clearly have one already.  The only thing that might motivate them to release one is a noisy thread.

**Comment by davama** [comment] 2023-07-05 11:35
> The only thing that might motivate them to release one is a noisy thread.

we can do like reddit users did and spam away 😆

hope they reply soon.

**Comment by azdolinski** [comment] 2023-07-13 20:13
```bash
$ cd /opt/docker/redis/
$ ls
data  docker-compose.yml
$ git clone https://github.com/RedisInsight/RedisInsight.git
$ ls
data  docker-compose.yml  RedisInsight
$ cat docker-compose.yml
version: '3'
services:
  redisinsight:
    container_name: redisinsight
    hostname: redisinsight
    build:
      context: RedisInsight
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - TZ=Europe/Warsaw
#    env_file:
#      - redisinsight.env
    volumes:
      -  /opt/docker/redis/data/redisinsight:/db
$ docker-compose up -d
```

On Synology ds920:
[+] Building 1507.5s (38/39)

**Comment by ViktarStarastsenka** [comment] 2023-07-17 12:11
hey, thank you for bringing up this thread, I understand and agree that the docker container is important.
We will define the exact timelines for the docker container in September-October.
I'll post an update with the timelines when they are set.

**Comment by Ashtonian** [comment] 2023-07-17 14:23
I'm a big fan of this project, but that seems a little crazy. 2.x was released over a year ago, thats 2/3 months away to set a future date to work on it, when there are already unofficial images showing up on dockerhub. Seems intentionally slow.

**Comment by LeonPatmore** [comment] 2023-08-17 16:00
:hi: Is there any update for this? Currently forced to use redis insight v1, which is a shame

**Comment by seebeen** [comment] 2023-08-17 17:19
I'm amazed that a huge company raking in billions of $ can't take the time to release a proper Docker image for v2.
It took me a day and a half to check out the source code, analyze the docker file, implement a full semantic release process and build images for both linux/amd64 and linux/arm64

https://github.com/oblakstudio/redisinsight
https://hub.docker.com/r/oblakstudio/redisinsight

*What do you get*
Every monday, my repo checks if there is a new release of RedisInsight - if so, it downloads the repo, 
updates my repo and starts the release process.

There are some caveats and hoops tho

**Caveat #1**
Images are being compiled on self-hosted runners.

**Why**

Due to dependency hell and specific build process, I won't even get into, it requires ubuntu 20+ to compile for linux/amd64, with a lot of build tools and specific dev libs.

SQLite 3 is such a pain in the ass

Due to another dependency hell (on frontend), yarn bugs, voodoo magic and other poor architectural decisions linux/arm64 version won't compile under QEMU. Tried 30+ builds on various machines- nothing, zip, nada. I managed to compile on my M1 Mac, but not on M2.

So I spun up an arm64 instance, installed same packages as on my ubuntu machine - and everything works like a charm.

**Caveat #2**

Dockerfile has been modified, and docker entry point too

**Why?**
Because avahi config is bugged beyond relief in docker networks - and I don't have the time to rework the setup so it works in all posible docker configurations.

https://bugzilla.redhat.com/show_bug.cgi?id=1471318
https://bugs.launchpad.net/ubuntu/+source/avahi/+bug/327362

Debian Image they are using has shown me that there are some heisen-bugs - build will fail even though it's cached, it will fail in random steps, yarn will throw a SEGFAULT or something like that. 
I updated to bullseye-slim and it works like a charm.

**Conclusion**

You get fully built docker image for amd64 and arm64, which works OOB, but doesn't have avahi and mdns, and isn't "oFiCCiAL". but it has a low disk and memory footprint, and works OOB in any possible docker configuration.

P.S. Caveat Emptor

**Comment by seebeen** [comment] 2023-08-17 20:20
I'll write a readme with all the possible environment variables, because official readme and guide is not needed. Code is self-documenting 👀👀👀

**Comment by erfantkerfan** [comment] 2023-09-03 12:59
+1
need 2.0 docker images

**Comment by seebeen** [comment] 2023-09-03 21:11
> +1 need 2.0 docker images

https://hub.docker.com/r/oblakstudio/redisinsight

**Comment by chalut01** [comment] 2023-09-06 02:47
+1

**Comment by m4n50n** [comment] 2023-09-06 10:36
+1

**Comment by ViktarStarastsenka** [comment] 2023-10-27 15:44
hi, we are targeting to release a docker image somewhere in January.
I'll post an update later with a more specific timeline.

**Comment by seebeen** [comment] 2023-10-29 14:51
> hi @LeonPatmore , no updates for now, they will be late in September or October

> an update: we are targeting to release an official docker image somewhere in January.

I'm betting $100 as a donation to any charity that their version will not be released in january.

**Comment by seebeen** [comment] 2023-10-31 20:19
Since this issue seems to be the official thread for the docker image, just to let everyone know we've released v2 branch of the docker image which tracks official upstream properly. 

@ViktarStarastsenka How about that bet mate? 😇

**Comment by lukechi1219** [comment] 2023-11-13 19:11
I already successfully build RedisInsight-2.36.0 image and run it in my develop environment.

Here's how I do it: https://chat.openai.com/share/553f1558-1966-48c6-ac77-a107328d910e

**Comment by tugtugtug** [comment] 2023-11-15 19:51
@ViktarStarastsenka  will the official image support setting up the default cluster automatically from envs, or arguments? One of the use case would be to deploy this docker with pre-defined cluster settings (readonly).

**Comment by ViktarStarastsenka** [comment] 2023-11-21 13:52
@tugtugtug , we are planning to add it, though it can be not in the first iteration.
by "read-only" do you mean that there will be no way to remove these databases from RedisInsight?

**Comment by erfantkerfan** [comment] 2023-11-21 15:14
Same here
Read only means the users can only use insight instance to connect to specific destinations and not other instances of redis

**Comment by tugtugtug** [comment] 2023-11-21 15:58
> Same here Read only means the users can only use insight instance to connect to specific destinations and not other instances of redis

@ViktarStarastsenka this is what I meant by read only cluster settings. We would not want the users to be able to alter any settings of the cluster, or point the service to somewhere else.

**Comment by ViktarStarastsenka** [comment] 2023-11-21 16:29
got it, by username and password should be editable, right?
can't promise that it will be added soon, but I'll add it to our Backlog and it will be prioritized a bit later

**Comment by tugtugtug** [comment] 2023-11-21 16:33
> @tugtugtug , @erfantkerfan , got it, but username and password should be editable, right? can't promise that it will be added soon, but I'll add it to our Backlog and it will be prioritized a bit later

Thanks a lot @ViktarStarastsenka! For our use case, even the username/password would be hidden from the user. Imagine we deploy RedisInsight to a k8s cluster, the users of the portal is to view, edit, monitor the activity of the services accessing the db, so the username/password would be the ones used by the services.

**Comment by ripper2hl** [comment] 2024-01-16 20:57
any news ? 🤔

**Comment by ViktarStarastsenka** [comment] 2024-01-18 13:52
we are planning to release the docker container around January 30.
One note - the first release will not contain all the features discussed in this thread (e.g. setting up databases via envs), they will be prioritized separately a bit later.

**Comment by ViktarStarastsenka** [comment] 2024-01-30 14:36
The RedisInsight Docker container will be released tomorrow.

@seebeen , can you make changes to the countdown?

**Comment by ViktarStarastsenka** [comment] 2024-01-31 17:24
@seebeen , regarding our bet, here is the equivalent of $100 to Unicef.
And Redis will match this donation as well.

<img width="897" alt="Screenshot 2024-01-31 at 18 19 02" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/36f3bec3-6cec-474c-a830-4dafb6175d75">

**Comment by ToshY** [comment] 2024-01-31 19:51
@ViktarStarastsenka 

I've just tested it and already love it ❤️ Respect for sticking to the deadline and keeping your promises 🥇

**Comment by ViktarStarastsenka** [comment] 2024-01-31 20:00
huge kudos to @arthosofteq (he is a real hero), @vlad-dargel , @mariasergeenko , @GnaneshKunal, @nelsonwellsredis for making this possible

**Comment by ViktarStarastsenka** [comment] 2024-01-31 20:09
Finally closing this ticket.

A couple of notes:
- a ticket to allow adding default database through environment variables - https://github.com/RedisInsight/RedisInsight/issues/289 // please upvote if it is relevant for you
- subpath proxy support will be added later
- examples of how to set up RedisInsight behind a reverse proxy will be provided and documented a bit later

**Closed by ViktarStarastsenka** 2024-01-31 20:09 UTC
Labels: feature

**Comment by seebeen** [comment] 2024-01-31 22:36
@ViktarStarastsenka Congratulations!!!!! Both to you and the redis team on releasing the Arm64 version of container.  
I'll czech out your version and maybe create bug reports / pull requests if something is amiss.

Regarding the donation - would you like me to donate to UNICEF as well?

P.S. Коли будеш у Белграді, подзвони мені, ми можемо випити пива 🍺🍺🍺

**Comment by mquinnfd** [comment] 2024-02-01 09:00
@seebeen what's your take on the official release vs. your one (in terms of the tailoring you did for `avahi daemon` etc.)

If I started a project today, which should I use? 🤔 

(this has been an unusually fun thread to follow, kudos to all involved 🤣)

**Comment by ViktarStarastsenka** [comment] 2024-02-02 14:08
@seebeen , would be very beneficial to get your feedback indeed.
Can you donate to [Friends of Animals](https://friendsofanimals.org/), as we initially discussed? Unicef was just my choice.
