### ISSUE TITLE
[Feature Request]:Show available database and size as dropdown

### ISSUE THREAD

**Issue by shamsheermh** [RedisInsight/RedisInsight#3852] opened 2024-09-22 14:06 UTC
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

<img width="337" alt="image" src="https://github.com/user-attachments/assets/e6942b2b-4f4e-42a7-ac25-524185d91b86">

**Comment by ViktarStarastsenka** [comment] 2024-09-23 06:32
hi @shamsheermh , this is a duplicate of https://github.com/RedisInsight/RedisInsight/issues/1857

**Closed by ViktarStarastsenka** 2024-09-23 06:32 UTC
Labels: feature
