### ISSUE TITLE
We need Chinese！！！

### ISSUE THREAD

**Issue by mojunyu** [RedisInsight/RedisInsight#3625] opened 2024-07-19 01:50 UTC
This software is awesome!
We need Chinese！！！
We need Chinese！！！
We need Chinese！！！

**Comment by ViktarStarastsenka** [comment] 2024-07-20 21:27
hi, this is a duplicate of https://github.com/RedisInsight/RedisInsight/issues/1317

**Closed by ViktarStarastsenka** 2024-07-20 21:27 UTC
Labels: feature
