### ISSUE TITLE
[Bug]: Passwords with the @ symbol

### ISSUE THREAD

**Issue by Meaningisuse** [RedisInsight/RedisInsight#3019] opened 2024-02-01 07:47 UTC
If the password contains the @ symbol, the connection will fail with an authentication error

<img width="518" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/15310195/7e9f49b8-ffb7-4366-9467-a6255108b354">

**Comment by ViktarStarastsenka** [comment] 2024-02-01 13:37
hi @Meaningisuse , do you insert connection details manually or do you use connection URLs?

**Comment by Meaningisuse** [comment] 2024-02-02 03:14
> do you insert connection details manually or do you use connection URLs

<img width="998" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/15310195/302e11e4-af9f-451f-8859-36bf885dc691">
![image](https://github.com/RedisInsight/RedisInsight/assets/15310195/89a3f188-22dd-4999-9322-ef79a58c69fe)

connecting through redis-cli is normal

**Comment by ViktarStarastsenka** [comment] 2024-02-02 11:05
@Meaningisuse , thank you.
I still can't reproduce this.
Could you send this additional information to help find the root cause:
- your OS
- RedisInsight version
- Redis version
- logs from `{users}/redisinsight-app/logs` (but please sanitize any sensitive information)
- also it would be helpful to get the server request, to find it you can open the Network tab in the dev tools (but remove any sensitive information from it).

**Comment by Meaningisuse** [comment] 2024-02-03 07:10
> @Meaningisuse , thank you. I still can't reproduce this. Could you send this additional information to help find the root cause:
> 
> * your OS
> * RedisInsight version
> * Redis version
> * logs from `{users}/redisinsight-app/logs` (but please sanitize any sensitive information)
> * also it would be helpful to get the server request, to find it you can open the Network tab in the dev tools (but remove any sensitive information from it).

- OS：macbook air m1 14.2.1
- RedisInsight version：2.42.0 
- Redis version：5.0.14
I don't find any log

**Comment by ViktarStarastsenka** [comment] 2024-02-05 17:09
@Meaningisuse , can you send the server request as well?
to find it you can open the Network tab in the dev tools (but remove any sensitive information from it).

**Comment by Meaningisuse** [comment] 2024-02-06 02:49
> @Meaningisuse , can you send the server request as well? to find it you can open the Network tab in the dev tools (but remove any sensitive information from it).

<img width="457" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/15310195/d672a897-56d6-4a9b-8eae-76782bc3caa8">
<img width="757" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/15310195/568ddc90-f572-4857-a518-0c0b6a256de9">
<img width="490" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/15310195/d8bb24fd-9bfb-43a0-b371-4be7430a086e">

**Comment by ViktarStarastsenka** [comment] 2024-02-29 14:15
@Meaningisuse , it should be fixed with 2.44.0 (released today).
Please reopen the ticket if the issue persists.

**Closed by ViktarStarastsenka** 2024-02-29 14:15 UTC
