### ISSUE TITLE
[Feature Request]:Connect multiple host at time without going back

### ISSUE THREAD

**Issue by shamsheermh** [RedisInsight/RedisInsight#3853] opened 2024-09-22 14:08 UTC
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).
<img width="862" alt="image" src="https://github.com/user-attachments/assets/9a15486d-2820-4b8d-adfb-634fa14c592c">

**Comment by ViktarStarastsenka** [comment] 2024-09-23 06:33
this is a duplicate of https://github.com/RedisInsight/RedisInsight/issues/1858

**Closed by ViktarStarastsenka** 2024-09-23 06:33 UTC
Labels: feature
