### ISSUE TITLE
[Feature Request]: Format JSON of Hash value

### ISSUE THREAD

**Issue by piavgh** [RedisInsight/RedisInsight#832] opened 2022-06-29 07:15 UTC
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
In Hash value, I have this:

```
{"reserveUsd":0.1345319322552176,"amplifiedTvl":0.1345319322552176,"swapFee":0.003,"exchange":"traderjoe","type":"uni","timestamp":1641330355,"reserves":["3745321053875768","2601651374"],"tokens":[{"address":"0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7","name":"","symbol":"","decimals":0,"weight":50,"swappable":true},{"address":"0xdc8211592727900ee08940dacddbc9da06daad12","name":"","symbol":"","decimals":0,"weight":50,"swappable":true}],"totalSupply":"3119165743615"}
```

This text should be formatted as JSON to something like:

```json
{
  "reserveUsd": 0.1345319322552176,
  "amplifiedTvl": 0.1345319322552176,
  "swapFee": 0.003,
  "exchange": "traderjoe",
  "type": "uni",
  "timestamp": 1641330355,
  "reserves": [
    "3745321053875768",
    "2601651374"
  ],
  "tokens": [
    {
      "address": "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7",
      "name": "",
      "symbol": "",
      "decimals": 0,
      "weight": 50,
      "swappable": true
    },
    {
      "address": "0xdc8211592727900ee08940dacddbc9da06daad12",
      "name": "",
      "symbol": "",
      "decimals": 0,
      "weight": 50,
      "swappable": true
    }
  ],
  "totalSupply": "3119165743615"
}
```

**How often do you encounter this problem** (Describe how frequently this problem occurs).
Always

**Alternatives considered** (Describe any alternative features or products you've considered).
https://apps.apple.com/us/app/medis-2-gui-for-redis/id1579200037

Unfortunately, the free version of Medis does not support filter by Hash field

**Additional information** (Add any other context or details here).

**Comment by CryptoTradee** [comment] 2022-07-27 23:05
Duplicate of https://github.com/RedisInsight/RedisInsight/issues/472?

**Comment by ViktarStarastsenka** [comment] 2022-08-23 22:47
hi @piavgh , please try it in 2.8.0.

**Closed by ViktarStarastsenka** 2022-08-23 22:47 UTC
Labels: feature
