### ISSUE TITLE
[Feature Request]: "Scan All" button in tree view

### ISSUE THREAD

**Issue by micbox** [RedisInsight/RedisInsight#1841] opened 2023-03-16 06:03 UTC
**Problem description**
To be able to **scan all keys** in DB (maybe via a special **"Scan All" button** in the treeview) when you know for sure you need to see the whole tree with sub-items in a specific Redis DB.

**How often do you encounter this problem**
Very frequently since I hold about million of items in my DB and loading just 10K items at once (or repeatedly pushing **"Scan more"** button) does not show the whole tree until almost all items are loaded.

**Alternatives considered**
Feature like this (automatic background scanning of all elements with the whole tree display) is pretty good implemented in RDM (now RESP.app). As an additional idea you can try implementing scanning/re-scanning all sub-keys under a specific item in the tree.

**Comment by ViktarStarastsenka** [comment] 2024-03-28 18:07
closing this ticket as a duplicate of https://github.com/RedisInsight/RedisInsight/issues/1841.
the status and updates will be posted there

**Closed by ViktarStarastsenka** 2024-03-28 18:07 UTC
Labels: feature
