### ISSUE TITLE
[Feature Request]:I hope there is a Chinese version

### ISSUE THREAD

**Issue by danjiaxin555** [RedisInsight/RedisInsight#4150] opened 2024-11-28 14:42 UTC
My English is not very good, I hope the author can support internationalization and provide a Chinese version, thank you

**Comment by ViktarStarastsenka** [comment] 2024-11-28 14:58
this is a duplicate of https://github.com/RedisInsight/RedisInsight/issues/1317

**Closed by ViktarStarastsenka** 2024-11-28 14:58 UTC
Labels: feature
