### ISSUE TITLE
[Feature Request]: about the way to select DB index

### ISSUE THREAD

**Issue by ksymmy** [RedisInsight/RedisInsight#2545] opened 2023-09-01 01:57 UTC
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
Currently, you can only enter numbers to complete the selection of the database,
I hope the official can use the drop-down box to select the database

**How often do you encounter this problem** (Describe how frequently this problem occurs).
always

**Alternatives considered** (Describe any alternative features or products you've considered).
se the drop-down box to select the database

**Additional information** (Add any other context or details here).

**Comment by iRubens** [comment] 2024-01-29 12:00
Same here, it would be very nice to see and select the actual database number.
In our case multiple database are used for test environments.

**Comment by ViktarStarastsenka** [comment] 2024-03-28 18:22
closing this ticket as this is a duplicate of https://github.com/RedisInsight/RedisInsight/issues/1857.

**Closed by ViktarStarastsenka** 2024-03-28 18:22 UTC
Labels: feature
