### ISSUE TITLE
[Feature Request]: redis-cluster - show know nodes and not only active nodes

### ISSUE THREAD

**Issue by raphaelauv** [RedisInsight/RedisInsight#3685] opened 2024-08-08 12:28 UTC
when we add a new nodes to a redis-cluster , the node is not serving shard 

so the command CLUSTER INFO give

```log
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:4
cluster_size:3
...
```
and commande CLUSTER NODES give

```log
127.0.0.1:6379> cluster nodes
e8e68fc1cf12a82beab1eb9f0fea508f5bede93b 172.22.0.3:6379@16379 master - 0 1723120018000 1 connected 0-5460
9cd2cd5173d6e63ef63c2d1aa35bf0818aa55e68 172.22.0.2:6379@16379 master - 0 1723120018548 3 connected 10923-16383
9780d740bb94ceb181d291d635876176e80f98fa 172.22.0.5:6379@16379 myself,master - 0 1723120017000 0 connected
b48c76bf97506eb454b584021da010fafd32245b 172.22.0.4:6379@16379 master - 0 1723120018447 2 connected 5461-10922

```
but redisinsight only show :

![image](https://github.com/user-attachments/assets/ed6db53f-63ba-4449-be04-83fbb1c4140f)

**Comment by ViktarStarastsenka** [comment] 2024-08-09 15:35
hi @raphaelauv , this ticket is a duplicate of https://github.com/RedisInsight/RedisInsight/issues/3035.

**Closed by ViktarStarastsenka** 2024-08-09 15:35 UTC
Labels: feature
